### ISSUE TITLE
Reinstate locale hack

### ISSUE THREAD

**Issue by t184256** [t184256/nix-on-droid-bootstrap#35]
We've dropped

```
{
  # Fix locale (perl apps panic without it)
  home.sessionVariables = {
    LOCALE_ARCHIVE = "${pkgs.glibcLocales}/lib/locale/locale-archive";
  };
}
```

This should be reinstated somehow somewhere.

**Comment by Gerschtli** [comment]
There are two ways to add this back in:

Either create a home-manager module, which we can add in the imports list in modules/home-manager.nix , or we create our own management of environment variables (which would be my preferred way because of the independence of home-manager).

The latter should be quite easy to implement, when we create a separate file containing the variables which we are sourcing in login-inner .

Will have a look at it when I got time :)
